### PR TITLE
Simplify Plugin API

### PR DESCRIPTION
**Pull request by eile**

### CODE REVIEW

**Comment by eile** [comment]
Do not merge yet - needs changes in Brion

**Comment by eile** [comment]
?

Brion does not compile with these changes, hence the do not merge comment. Working on it.

**Comment by hernando** [comment]
I didn't see your comment about Brion, maybe I had already started reviewing.

**Comment by hernando** [comment]
You should have made this PR on a branch, then Brion CI would have passed.

**Comment by eile** [comment]
No, because the rebase-and-merge will change the SHA. Downstream projects needs a touch in any case.

**Comment by hernando** [comment]
Yes and no. With simple merge it works, I know it's not ideal, but until Github figures out that fast forward merges do exist we have to pay the price of ugly history or retrigger CI testing.

**Pull request merged**
