### PR TITLE
PluginFactory correctly ignores to clean up open DSO plugins on exit

### PR DESCRIPTION
**Pull request by eile**

### CODE REVIEW

**Comment by rdumusc** [comment]
I don't understand the problematic as well as you do, but I haven't observed problems with the deregister call myself? On the contrary, I just tested the spikeConverter with valgrind and it reports memory leaks if this deregister called is removed... Go ahead if you're really sure of what you are doing, but I have some doubts...

**Comment by eile** [comment]
It depends on the order the DSOs are unloaded at exit, so on your system the PluginFactory static dtor gets called before the plugin DSO is unloaded... on my system it's the other way around. The app should call deregisterAll before exiting main() to fix the memleak.

**Comment by rdumusc** [comment]
OK, then that would require additions to the Brion API. Right now the SpikePluginFactory is completely hidden from the user...

**Comment by eile** [comment]
Agreed, but it's not so important. You are after main() already, so in any case the OS will release the memory.

**Pull request merged**
