### PR TITLE
Thread-safe memcached impl

### PR DESCRIPTION
**Pull request by tribal-tec**

### CODE REVIEW

**Comment by eile** [comment]
Should this be in this impl? Afaik neither the leveldb nor skv backend are thread-safe either. The scalable solution for memcached would be one cache instance per thread.

**Comment by eile** [comment]
Should this be in this impl? Afaik neither the leveldb nor skv backend are thread-safe either. The scalable solution for memcached would be one cache instance per thread.

**Comment by tribal-tec** [comment]
The per-thread memcached was not very stable and didn't scale, so definitely not now. Read access should be thread-safe imo, write could be argued to be serialized by user code. Multiple memcached instances behave not stable right now, I have to do more investigations today.

**Comment by eile** [comment]
Ok. Shall we move the locking then up one level so it affects leveldb as well? I guess the skv impl will go the way of the dodo soon.

**Pull request closed without merging**
