### PR TITLE
Static linking fixes

### PR DESCRIPTION
**Pull request by tribal-tec**

### CODE REVIEW

**Comment by tribal-tec** [comment]
retest this please

**Comment by tribal-tec** [comment]
retest this please

**Comment by tribal-tec** [comment]
Retest this please

**Comment by tribal-tec** [comment]
retry

**Comment by tribal-tec** [comment]
Retest this please

**Comment by mgeplf** [comment]
Cool, when I get a chance, I'll finish the wheel building.   Not sure, though, if I'll be able to do it this week, with the hackathon thing.

**Pull request merged**
