### PR TITLE
memory performance test

### PR DESCRIPTION
**Pull request by eile**

### CODE REVIEW

**Comment by tribal-tec** [comment]
Retest this please

**Comment by tribal-tec** [comment]
The build uses the wrong CMake subtree!?!?

**Comment by eile** [comment]
Nope, Jenkins uses ctest directly, not make test. See https://bbpcode.epfl.ch/code/#/c/8286/

**Comment by eile** [comment]
Retest this please

**Comment by eile** [comment]
Retest this please

**Comment by tribal-tec** [comment]
Retest this please

**Pull request merged**
